# Site settings
title: 长刀, 一个老程序员. 
email: jameslau@263.net
description: > # this means to ignore newlines until "baseurl:"
     老程序员.
     热爱编程，享受编程。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://changdao.github.io" # the base hostname & protocol for your site
github_username: Changdao 

# Build settings
markdown: kramdown
