# Site settings
title: Changdao, an old programmer. 
email: jameslau@263.net
description: > # this means to ignore newlines until "baseurl:"
     A programmer.
     Love it, enjoy it
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://changdao.github.io" # the base hostname & protocol for your site
github_username: Changdao 

# Build settings
markdown: kramdown
