# Site settings
title: Changdao, an old programmer. 
email: jameslau@263.net
description: > # this means to ignore newlines until "baseurl:"
     I love and program for twenty years. I still love programming.
     I love to share my opinions about programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://changdao.github.io" # the base hostname & protocol for your site
twitter_username: Not registered yet! 
github_username: Changdao 

# Build settings
markdown: kramdown
